# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9db985be304d1a8f16d0dac36fb88024cb04ba6ddf406f2167f9e7985de1d7826604f8e5f452698d6a703fccf68707efffa14b45f355436a574064913029fdb5

test:
  secret_key_base: de89400d0be3ab8891e41569e7265e8b469e7bad43ac1f69f3a95f9b5080369d2473089c32f51dc523fd0af771ac2d5daca75cb24598b9a105d622f5d11cdaec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
